site_name: Ryūtsuchi
nav:
  - Sessioni:
    - Sessione 1: Sessioni/2025-08-12.md
    - Sessione 2: Sessioni/2025-08-30.md
    - Sessione 3: Sessioni/2025-09-20.md
    - Sessione 4: Sessioni/2025-10-11.md
    - Sessione 5: Sessioni/2025-10-25.md
    - Sessione 6: Sessioni/2025-11-15.md
    - Sessione 7: Sessioni/2025-11-29.md
    - Sessione 8: Sessioni/2025-12-13.md
    - Sessione 9: Sessioni/2025-12-27.md
  - Personaggi:
    - Alessandro: Izumi.md
    - Giacomo: Mizuhara.md
    - Veronica: Hecate.md
  - Luoghi:
    - Shinkai no Kuni:
      - Shinkai no Kuni: Shinkai no Kuni.md
      - Murasame: Murasame.md
      - Residenza: Residenza.md
    - Monte Torii: Monte Torii.md
  - NPC:
    - Clan Mori: Mori.md
    - George: George Mastro Tahl.md
  - Lore:
    - Armi Divine: Armi Divine.md
    - Wyvern:
      - Wyvern: Wyvern.md
      - Jyuratodus: Jyuratodus.md
      - Gran Jagras: Gran Jagras.md
  - Oggetti:
    - Mappa: Mappa.md
  - Quest:
    - Coboldi Balordi: Quest/Coboldi Balordi.md
# theme: torillic
docs_dir: Note
plugins:
  - search
markdown_extensions:
  - wikilinks
