site_name: Ryūtsuchi
nav:
  - Sessioni:
    - Sessione 1: Sessioni/001.md
    - Sessione 2: Sessioni/002.md
    - Sessione 3: Sessioni/003.md
    - Sessione 4: Sessioni/004.md
    - Sessione 5: Sessioni/005.md
    - Sessione 6: Sessioni/006.md
    - Sessione 7: Sessioni/007.md
    - Sessione 8: Sessioni/008.md
    - Sessione 9: Sessioni/009.md
    - Sessione 10: Sessioni/010.md
  - Personaggi:
    - Alessandro: Izumi.md
    - Giacomo: Mizuhara.md
    - Veronica: Hecate.md
  - Luoghi:
    - Shinkai no Kuni:
      - Shinkai no Kuni: Shinkai no Kuni.md
      - Murasame: Murasame.md
      - Residenza: Residenza.md
    - Monte Torii: Monte Torii.md
  - NPC:
    - Clan Mori: Mori.md
    - George: George Mastro Tahl.md
  - Lore:
    - Armi Divine: Armi Divine.md
    - Draghi Leggendari: Draghi Leggendari.md
    - Wyvern:
      - Wyvern: Wyvern.md
      - Jyuratodus: Jyuratodus.md
      - Gran Jagras: Gran Jagras.md
  - Oggetti:
    - Mappa: Mappa.md
  - Quest:
    - Coboldi Balordi: Quest/Coboldi Balordi.md
# theme: torillic
docs_dir: Note
plugins:
  - search
markdown_extensions:
  - wikilinks
